In [1]:
import torch
x = torch.empty(5,3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [2]:
x = torch.rand(5,3)
print(x)

tensor([[0.4687, 0.9756, 0.9725],
        [0.1222, 0.5272, 0.2786],
        [0.4118, 0.8682, 0.4683],
        [0.9880, 0.9915, 0.8913],
        [0.1341, 0.4156, 0.7858]])


In [3]:
x = torch.zeros(5,3,dtype = torch.long)

In [4]:
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5,3,dtype = torch.float64)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x = torch.randn_like(x,dtype = torch.float) #和上一个维度一样
print(x)

tensor([[ 0.2074,  0.2691, -0.5212],
        [-0.8469,  1.5516, -1.6979],
        [ 0.1566,  0.9243, -0.1622],
        [ 0.8173, -0.7650, -1.2201],
        [-1.5500, -1.7255, -0.5591]])


In [8]:
print(x.shape)
print(x.size())

torch.Size([5, 3])
torch.Size([5, 3])


In [9]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 0.6410,  1.1402, -0.3128],
        [-0.7487,  2.3085, -1.3378],
        [ 0.4152,  1.1968,  0.7651],
        [ 1.6874, -0.0983, -0.6134],
        [-0.7012, -0.7656,  0.4051]])


In [10]:
print(torch.add(x,y))

tensor([[ 0.6410,  1.1402, -0.3128],
        [-0.7487,  2.3085, -1.3378],
        [ 0.4152,  1.1968,  0.7651],
        [ 1.6874, -0.0983, -0.6134],
        [-0.7012, -0.7656,  0.4051]])


In [11]:
result = torch.empty(5,3)
torch.add(x,y,out = result) #指定输出到result中

tensor([[ 0.6410,  1.1402, -0.3128],
        [-0.7487,  2.3085, -1.3378],
        [ 0.4152,  1.1968,  0.7651],
        [ 1.6874, -0.0983, -0.6134],
        [-0.7012, -0.7656,  0.4051]])

In [12]:
print(result)

tensor([[ 0.6410,  1.1402, -0.3128],
        [-0.7487,  2.3085, -1.3378],
        [ 0.4152,  1.1968,  0.7651],
        [ 1.6874, -0.0983, -0.6134],
        [-0.7012, -0.7656,  0.4051]])


In [13]:
y.add_(x)
print(y)

tensor([[ 0.6410,  1.1402, -0.3128],
        [-0.7487,  2.3085, -1.3378],
        [ 0.4152,  1.1968,  0.7651],
        [ 1.6874, -0.0983, -0.6134],
        [-0.7012, -0.7656,  0.4051]])


In [14]:
y = x[0, :]
y = y+1
print(y)
print(x[0, :])


tensor([1.2074, 1.2691, 0.4788])
tensor([ 0.2074,  0.2691, -0.5212])


In [15]:
y = x.view(15)
z = x.view(-1,5) #参数-1可以根据另一维度自动计算
print(x.size(),y.size(),z.shape)

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [16]:
x +=1
print(x)
print(y)

tensor([[ 1.2074,  1.2691,  0.4788],
        [ 0.1531,  2.5516, -0.6979],
        [ 1.1566,  1.9243,  0.8378],
        [ 1.8173,  0.2350, -0.2201],
        [-0.5500, -0.7255,  0.4409]])
tensor([ 1.2074,  1.2691,  0.4788,  0.1531,  2.5516, -0.6979,  1.1566,  1.9243,
         0.8378,  1.8173,  0.2350, -0.2201, -0.5500, -0.7255,  0.4409])


In [17]:
x_cp = x.clone().view(15) #clone是简单地传值 而非引用
x -= 1
print(x)
print(x_cp)

tensor([[ 0.2074,  0.2691, -0.5212],
        [-0.8469,  1.5516, -1.6979],
        [ 0.1566,  0.9243, -0.1622],
        [ 0.8173, -0.7650, -1.2201],
        [-1.5500, -1.7255, -0.5591]])
tensor([ 1.2074,  1.2691,  0.4788,  0.1531,  2.5516, -0.6979,  1.1566,  1.9243,
         0.8378,  1.8173,  0.2350, -0.2201, -0.5500, -0.7255,  0.4409])


In [18]:
x = torch.randn(1)
print(x)
print(x.item()) #获得x的标量值

tensor([1.3031])
1.303123116493225


In [19]:
#广播机制↓

In [20]:
x = torch.arange(1,4).view(1,3)
print(x)
y = torch.arange(1,5).view(4,1)
print(y)
print(x+y)

tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6],
        [5, 6, 7]])


In [21]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])
id_before = id(y)
y = y+x           #这一步会开辟新内存，y的地址变了
print(id(y) == id_before)

False


In [22]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])
id_before = id(y)
y[:] = y+x          #这一步使用[:]索引，不开辟新内存
print(id(y) == id_before)

True


In [23]:
a = torch.ones(5)
b = a.numpy()
print(a,b)
#numpy 和 tensor 共享内存地址
a +=1
print(a,b)
b +=1
print(a,b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [24]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a,b)
#numpy 和 tensor 共享内存地址
a +=1
print(a,b)
b +=1
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [25]:
c = torch.tensor(a) #该方法会进行数据拷贝，不共享内存
a+=1
print(a,c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [26]:
x = torch.ones(2,2, requires_grad = True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [27]:
y = x+2
print(y)
print(y.grad_fn) #y是通过一个加法操作创建的，这个有值

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [28]:
print(x.is_leaf,y.is_leaf) #直接创建的是叶子结点

True False


In [29]:
z = y*y*3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [30]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True) #改变属性
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


In [31]:
out.backward()

In [32]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [33]:
out2 = x.sum()
out2.backward()
print(x.grad)
#累计了上面的4.5 ，应该先清零


tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])


In [34]:
out3 = x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


In [35]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)
y = 2*x    #y是张量的时候需要一个tensor参数，将其转化为标量
z = y.view(2,2)
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)


In [36]:
v = torch.tensor([[1.0,0.1],[0.01,0.001]],dtype=torch.float)
z.backward(v)
print(x.grad)

tensor([2.0000, 0.2000, 0.0200, 0.0020])


In [37]:
x = torch.tensor(1.0,requires_grad=True)
y1 = x ** 2
with torch.no_grad():
    y2 = x ** 3
y3 = y1+y2
print(x.requires_grad)
print(y1,y1.requires_grad)
print(y2,y2.requires_grad)
print(y3,y3.requires_grad)

True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<ThAddBackward>) True


In [38]:
y3.backward() #y3 = x方+x三次方,y2梯度不回传
print(x.grad) #结果是2不是5

tensor(2.)


In [39]:
x = torch.ones(1,requires_grad=True)

print(x.data) #x.data独立于计算图之外
print(x.data.requires_grad) #不计算梯度

y =2*x
x.data *= 100

y.backward()
print(x)
print(x.grad)

tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])
