In [2]:
import torch
x = torch.empty(5,3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [2]:
x = torch.rand(5,3)
print(x)

tensor([[0.2509, 0.7522, 0.6970],
        [0.9390, 0.7422, 0.9906],
        [0.2022, 0.9211, 0.1631],
        [0.7041, 0.6378, 0.7001],
        [0.8914, 0.7559, 0.4296]])


In [3]:
x = torch.zeros(5,3,dtype = torch.long)

In [4]:
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
x = x.new_ones(5,3,dtype = torch.float64)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [11]:
x = torch.randn_like(x,dtype = torch.float) #和上一个维度一样
print(x)

tensor([[ 0.5488,  0.7304, -0.7221],
        [ 0.1009,  0.8443,  0.7681],
        [-1.2103, -1.8648, -0.0964],
        [ 0.5087, -0.0786,  0.4147],
        [ 1.2815,  0.0656, -0.1805]])


In [13]:
print(x.shape)
print(x.size())

torch.Size([5, 3])
torch.Size([5, 3])


In [14]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 1.0527,  1.1709, -0.6456],
        [ 0.1970,  1.2111,  1.4287],
        [-1.1557, -1.3262,  0.5683],
        [ 0.8680,  0.3241,  0.9467],
        [ 1.9657,  0.8882, -0.0071]])


In [15]:
print(torch.add(x,y))

tensor([[ 1.0527,  1.1709, -0.6456],
        [ 0.1970,  1.2111,  1.4287],
        [-1.1557, -1.3262,  0.5683],
        [ 0.8680,  0.3241,  0.9467],
        [ 1.9657,  0.8882, -0.0071]])


In [16]:
result = torch.empty(5,3)
torch.add(x,y,out = result) #指定输出到result中

tensor([[ 1.0527,  1.1709, -0.6456],
        [ 0.1970,  1.2111,  1.4287],
        [-1.1557, -1.3262,  0.5683],
        [ 0.8680,  0.3241,  0.9467],
        [ 1.9657,  0.8882, -0.0071]])

In [17]:
print(result)

tensor([[ 1.0527,  1.1709, -0.6456],
        [ 0.1970,  1.2111,  1.4287],
        [-1.1557, -1.3262,  0.5683],
        [ 0.8680,  0.3241,  0.9467],
        [ 1.9657,  0.8882, -0.0071]])


In [29]:
y.add_(x)
print(y)

RuntimeError: expand(torch.FloatTensor{[5, 3]}, size=[15]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)

In [23]:
y = x[0, :]
y = y+1
print(y)
print(x[0, :])


tensor([ 1.7304,  1.8443, -0.8648,  0.9214,  1.0656])
tensor([ 0.5488,  0.7304, -0.7221])


In [28]:
y = x.view(15)
z = x.view(-1,5) #参数-1可以根据另一维度自动计算
print(x.size(),y.size(),z.shape)

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [30]:
x +=1
print(x)
print(y)

tensor([[ 1.5488,  1.7304,  0.2779],
        [ 1.1009,  1.8443,  1.7681],
        [-0.2103, -0.8648,  0.9036],
        [ 1.5087,  0.9214,  1.4147],
        [ 2.2815,  1.0656,  0.8195]])
tensor([ 1.5488,  1.7304,  0.2779,  1.1009,  1.8443,  1.7681, -0.2103, -0.8648,
         0.9036,  1.5087,  0.9214,  1.4147,  2.2815,  1.0656,  0.8195])


In [31]:
x_cp = x.clone().view(15) #clone是简单地传值 而非引用
x -= 1
print(x)
print(x_cp)

tensor([[ 0.5488,  0.7304, -0.7221],
        [ 0.1009,  0.8443,  0.7681],
        [-1.2103, -1.8648, -0.0964],
        [ 0.5087, -0.0786,  0.4147],
        [ 1.2815,  0.0656, -0.1805]])
tensor([ 1.5488,  1.7304,  0.2779,  1.1009,  1.8443,  1.7681, -0.2103, -0.8648,
         0.9036,  1.5087,  0.9214,  1.4147,  2.2815,  1.0656,  0.8195])


In [34]:
x = torch.randn(1)
print(x)
print(x.item()) #获得x的标量值

tensor([-1.0113])
-1.011311650276184


In [ ]:
#广播机制↓

In [33]:
x = torch.arange(1,4).view(1,3)
print(x)
y = torch.arange(1,5).view(4,1)
print(y)
print(x+y)

tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6],
        [5, 6, 7]])


In [36]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])
id_before = id(y)
y = y+x           #这一步会开辟新内存，y的地址变了
print(id(y) == id_before)

False


In [38]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])
id_before = id(y)
y[:] = y+x          #这一步使用[:]索引，不开辟新内存
print(id(y) == id_before)

True


In [3]:
a = torch.ones(5)
b = a.numpy()
print(a,b)
#numpy 和 tensor 共享内存地址
a +=1
print(a,b)
b +=1
print(a,b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [4]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a,b)
#numpy 和 tensor 共享内存地址
a +=1
print(a,b)
b +=1
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [6]:
c = torch.tensor(a) #该方法会进行数据拷贝，不共享内存
a+=1
print(a,c)

[5. 5. 5. 5. 5.] tensor([4., 4., 4., 4., 4.], dtype=torch.float64)


In [7]:
x = torch.ones(2,2, requires_grad = True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [8]:
y = x+2
print(y)
print(y.grad_fn) #y是通过一个加法操作创建的，这个有值

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [9]:
print(x.is_leaf,y.is_leaf) #直接创建的是叶子结点

True False


In [10]:
z = y*y*3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [11]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True) #改变属性
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


In [12]:
out.backward()

In [13]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [14]:
out2 = x.sum()
out2.backward()
print(x.grad)
#累计了上面的4.5 ，应该先清零


tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])


In [15]:
out3 = x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


In [19]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)
y = 2*x    #y是张量的时候需要一个tensor参数，将其转化为标量
z = y.view(2,2)
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)
None


In [17]:
v = torch.tensor([[1.0,0.1],[0.01,0.001]],dtype=torch.float)
z.backward(v)
print(x.grad)

tensor([2.0000, 0.2000, 0.0200, 0.0020])


In [20]:
x = torch.tensor(1.0,requires_grad=True)
y1 = x ** 2
with torch.no_grad():
    y2 = x ** 3
y3 = y1+y2
print(x.requires_grad)
print(y1,y1.requires_grad)
print(y2,y2.requires_grad)
print(y3,y3.requires_grad)

True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<ThAddBackward>) True


In [21]:
y3.backward() #y3 = x方+x三次方,y2梯度不回传
print(x.grad) #结果是2不是5

tensor(2.)


In [22]:
x = torch.ones(1,requires_grad=True)

print(x.data) #x.data独立于计算图之外
print(x.data.requires_grad) #不计算梯度

y =2*x
x.data *= 100

y.backward()
print(x)
print(x.grad)

tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])
